### ISSUE TITLE
multiply function in def create_model

### ISSUE THREAD

**Issue by Mohamed-DL** [javid-norouzi/SAR-Image-Despeckling-Using-CNN-#4]
Hi again, I am sorry I would ask when you created the model function(def create_model), why did you use the multiply function here (as shown in the code below) rather than division as figure 2 shows in the paper?

x= tf.math.multiply(input_layer,x)
x=tf.math.tanh(x) 

Thank you

**Comment by ShowStopperTheSecond** [comment]
Hi 
For two reasons:
1) The noise is multiplicative and it's safe to use division as division is  a kind of multiplication
2) At the beginning of the training and in regions with intensity value of 0 the estimated noise would be also zero and division by zero is is not defined and you would have no gradient to back propagate 

You can experiment yourself. Check out what happens when you use multiplication

**Comment by Mohamed-DL** [comment]
Thank you for your answer.
